config/routes.rb
Rails.application.routes.draw do
  
  #get 'feedback/index'
  root :to => 'home#index'
  #get 'feedback/new'
  mount ShopifyApp::Engine, at: '/'
  get 'newpage', to: "home#newpage", as: 'newpage'
  #match '/reversestring' => 'home#reversestring', via: :get
  
  resources :surveys

  resources :feedbacks
  resources :questions do
    collection do
      post :import
    end
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer_category.rb
class AnswerCategory < ApplicationRecord
  validates :category, presence: true
  has_many :answer_option
  has_many :question
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  has_many :feedbacks
  belongs_to :answer_category
  has_many :surveys, through: :feedbacks
  has_many :questions, through: :surveys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :survey
  belongs_to :answer_option
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :surveys
  belongs_to :answer_category
  has_many :feedbacks, through: :surveys
  has_many :answer_options, through: :feedbacks

  require 'csv'

  def self.my_import(file)    
    CSV.foreach(file.path, headers:true) do |row|
      # 1st column is question, 2nd is category and remaining is answer options
      if row.length > 2 
        AnswerCategory.create({
          :category => row[1]})

        anscatid = AnswerCategory.where(category: row[1]).pluck(:id)
        puts anscatid
        Question.create({
          :survey_question => row[0],
          :answer_category_id => anscatid[0]
        })
        # Looping from 3 column till end to store answer options
        for i in 2..row.length-1 do
          AnswerOption.create({
            :survey_answer_option => row[i],
            :answer_category_id => anscatid[0]
          })
        end 

        
      end
    end
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :question
  has_many :feedbacks
  has_many :answer_options, through: :feedbacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @fb = Feedback.all
   
  end
  
  def new
    @fbquestions = Question.select(:survey_question, :answer_category_id, :'surveys.survey_code', :'surveys.question_id',:'surveys.id').joins(:surveys)

  end

  def create
    puts "Got params"
    puts params[:@customer_id]
    if params.has_key?(:feedbacks)
      params[:feedbacks].keys.each do |newq|
        puts "Response to " + newq + " is " + params[:feedbacks][newq]["response"]
        @new_fb=Feedback.new({ :survey_id => newq, :answer_option_id => params[:feedbacks][newq]["response"],:customer_id => params[:@customer_id]})
        @new_fb.save
      end
    else
      puts "no feedbacks!!!!!!!!!!!"
      # redirect_to request.referrer, flash: {notice: "Successfully checked in"}
    end
    redirect_to '/feedbacks'
  end

  def get_answer_options(ans_category_id)
    @ans = AnswerOption.where(answer_category_id: ans_category_id)
  end
  helper_method :get_answer_options

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthenticatedController
  def index
    #byebug
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)
    #byebug
    @orders = ShopifyAPI::Order.find(:all)
    @order_date = @orders.select{|order| I18n.l order.processed_at.to_time, format: "%m/%d/%Y" == '2019-11-28' }
    #@users = ShopifyAPI::User.find(:all)
    #@analytics = ShopifyAPI::Analytic.find(:all)

    @orders_qty = Hash.new(0)
    @orders.each do |order|
      order.line_items.each do |lineitem|
        puts "order# - #{order.order_number}"
        puts "Product id - #{lineitem.product_id}"
        puts "Quantity - #{lineitem.quantity}"
        @orders_qty[lineitem.product_id] += lineitem.quantity
      end
    end  
    #@chart = Feedback.joins(:answer_option, :survey)#.select(:survey_question, :survey_answer_option)
    # @chart = (
    #           (
    #             Survey.select(:'questions.survey_question',:id).joins(:question)
    #           ).
    #           select(:survey_question,:id,:'feedbacks.answer_option_id').joins(:feedback)
    #         ).select(:survey_question,:id,:answer_option_id,:'answer_options.survey_answer_option').joins(:answer_option)
    #@chart=Feedback.select(:'surveys.question_id', :survey_id, :answer_option_id).joins(:survey).
     #       select(:'questions.survey_question', :question_id, :survey_id, :answer_option_id ).joins(:question).
      #      select(:survey_question, :question_id, :survey_id, :answer_option_id, #:'answer_options.survey_answer_option').joins(:answer_options)
    #@chart=AnswerOption.select(:'feedbacks.answer_option_id', :'feedbacks.survey_id', :survey_answer_option).joins(:feedbacks).select(:'surveys.question_id', :'feedbacks.answer_option_id', :'feedbacks.survey_id', :survey_answer_question).joins(:surveys).select(:'questions.survey_question', :'surveys.question_id', :'feedbacks.answer_option_id', :'feedbacks.survey_id', :survey_answer_question).joins(:questions)     

    sql = "SELECT * FROM
            feedbacks fb,
            answer_options ao,
            surveys s,
            questions q
            WHERE fb.survey_id = s.id
            AND fb.answer_option_id = ao.id
            AND s.question_id = q.id" 
    
    
    @sql_result=Feedback.connection.select_all(sql)

    #puts @sql_result.columns
    puts @sql_result.length
    @chart=Hash.new()
    # creates a hash @chart for the charts. @chart[question][[answer][answer count]] => hash[key,value=[key,value]]
    @sql_result.each do |row|
      puts row['survey_question'] + " " + row['survey_answer_option']
      if @chart.key?(row['survey_question'])
        @chart[row['survey_question']][row['survey_answer_option']]+=1
      else
        @chart[row['survey_question']]=Hash.new(0)
        @chart[row['survey_question']][row['survey_answer_question']]=1
      end
    end
   
    # puts "List of questions:"
    # puts @chart.keys
    # @chart.keys.each do |q|
    #   puts q + ":" + @chart[q].keys.to_s
    #   @chart[q].except(nil).keys.each do |ans|
    #     puts "  " + ans.to_s + " = " + @chart[q][ans].to_s
    #   end
    # end
  end


end

app/controllers/questions_controller.rb
class QuestionsController < AuthenticatedController
  def index
    @questions = Question.all
    @answers = AnswerOption.all
    @aq = AnswerCategory.all
  end
  
  def new
    @question = Question.new
    @ans_cat = AnswerCategory.all
  end

  def get_answers(ans_category_id)
    @ans_for_category = AnswerOption.where(answer_category_id: ans_category_id)
  end
  helper_method :get_answers

  def import
    Question.my_import(params[:file])
    #my_import(params[:file],current_user.id)
    redirect_to root_url, notice: "Successfully Imported Questions Data!!!"
  end
end

app/controllers/surveys_controller.rb
class SurveysController < AuthenticatedController
  
  def index
   
    @surveys = Survey.all
    
    @q = Question.select(:survey_question, :answer_category_id, :'surveys.survey_code', :'surveys.survey_desc',:'surveys.question_id',:'surveys.id').joins(:surveys)
  end


  def new
    @questions = Question.all
    @surveys = Survey.new
  end

  def create
    params[:survey][:question_id].each do |newq|
      new_survey={:survey_code => params[:survey][:survey_code],
                  :survey_desc => params[:survey][:survey_desc],
                  :question_id => newq}
      #@survey = Survey.new(survey_params(newq))
      @survey=Survey.new(new_survey)
      @survey.save
    end
    redirect_to '/surveys'
  end

  private
  def survey_params
    params.require(:survey).permit(:survey_code, :survey_desc, :question_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/feedbacks/_form.html.erb
<body>
<form id="fb-form" action="/feedbacks" method="post"> 
<input type="hidden" name="authenticity_token" value="dummy" />

  <% @fbquestions.each do |q| %>  
    <div id="blk">  
    <label for="q"> <%= q.survey_question%></label>

    <% @ans = get_answer_options(q.answer_category_id) %><br>    
    <% @ans.each do |a| %>
      <%= radio_button_tag "feedbacks["+q.id.to_s+"][response]", a.id%> <%= a.survey_answer_option%><br>
      <%= hidden_field_tag '@customer_id', params[:id] %>
    <% end %>   
    <br>
    </div>
  <% end %>

  <br>
  <input type="submit" value="Submit">

 
</form>
</body>







<% if false %>
############# Comment start #################

<%= form_with scope: @tempfb, url: feedbacks_path, local: true do |form| %>
  <%= puts "############# #{@fbquestions}"%>


  <% @fbquestions.each do |q| %>

    <div class="field">
      <%= form.label q.survey_question%>
      <%= form.collection_select(:answer_option_id,  AnswerOption.where(answer_category_id: answer_category_id), :id, :survey_answer_option, {}, {})%> 
      <%= hidden_field_tag :survey_id, q.id %>
    </div>
  <% end %>
  
  

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>



<%= form_with url: "/feedbacks" do |form| %>
  <% @qid = 0 %>
  <% @fbquestions.each do |q| %>
    <%= form.label q.survey_question%>
    <% @ans = AnswerOption.where(answer_category_id: q.answer_category_id) %><br>
    <% @ans.each do |a| %>
        <%= radio_button_tag "feedbacks["+@qid.to_s+"][response]", a.id%> <%= a.survey_answer_option%><br>
    <% end %>
    <% @qid += 1 %>

  <% end %>
  
  <input type="submit" value="Submit">
<% end %>
<label for="q" <%=@qid%>> <%= q.survey_question%></label>
############# Comment start #################
<% end %>

app/views/feedbacks/index.html.erb
<h2> Thank you for providing feedback!! </h2>
<h2> Please close the window. </h2>

app/views/feedbacks/new.html.erb
<h1>SURVEY</h1>
<%= render 'form' %>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>

<p id="notice"><%= notice %></p>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Survey
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/surveys">View Surveys</a>
          <a class="dropdown-item" href="/surveys/new">Add new Survey</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Questions and Answers
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/questions/new">Import questions</a>
          <a class="dropdown-item" href="/questions">View available Questions and Answers</a>
          <div class="dropdown-divider"></div>          
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


<% if false %>
<%= bar_chart @chart.group(:survey_answer_option).count(:survey_answer_option) %>
<% end %>

<table>    
  <% @chart.keys.each do |q| %>
    <tr>
      <td>
        <%= column_chart(@chart[q].except(nil), title: q) %>
      </td>
      <td>
        <%= pie_chart(@chart[q].except(nil), title:q) %>
      </td>
    </tr>
  <% end %>
</table>




<%if false %>
<h2>The link to another page!!</h2>
<%= link_to 'Back', newpage_path, :target => "_blank" %>
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, "https://#{@shop_session.domain}/admin/products/#{product.id}", target: "_top" %></li> : 
    
  <% end %>
  <li><%= @products[0].id   %></li>

</ul>

<hr>
<h2> Orders </h2>
<ul>
<table>
  <thead>
  
    <tr>
      <th>Product id</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  
  </thead>
  <tbody>
 
    <% @orders_qty.each do |key , value|%>
      <tr>
        <td><%=key%></td>
        <td><%=value%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</ul>
<hr>
<table>
  <head>
  </head>
  <body>
    
    <% @order_date.each do |order|%>
      <tr>
        <td><%=order.order_number%></td>
        <td><%=I18n.l order.processed_at.to_time, format: "%m/%d/%Y"%></td>
        <td><%=order.total_price%></td>
      </tr>
    <% end %>
  </body>
</table>
<hr>

<h2>Webhooks</h2>

<% if @webhooks.present? %>
  <ul>
    <% @webhooks.each do |webhook| %>
      <li><%= webhook.topic %> : <%= webhook.address %></li>
    <% end %>
  </ul>
<% else %>
  <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
<% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pollapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: ("https://#{ @shop_session.url }" if @shop_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/questions/_form.html.erb
<hr>
<h2> Answer Category </h2>
<table>
  <thead>
    <tr>    
      <th>Answer Category id</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @aq.each do |q| %>
      <tr>
        <td><%= q.id%></td>
        <td><%= q.category%></td>
      </tr>
    <% end%>
  </tbody>
</table>
<hr>
<h2> Questions </h2>
<table>
  <thead>
    <tr>    
      <th>Questions id</th>
      <th>Questions</th>
      <th>Answer Category id</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |q| %>
      <tr>
        <td><%= q.id%></td>
        <td><%= q.survey_question%></td>
        <td><%= q.answer_category_id%></td>
      </tr>
    <% end%>
  </tbody>
</table>
<hr>
<h2> Answer Options </h2>
<table>
  <thead>
    <tr>    
      <th>Answer id</th>
      <th>Answer Category id</th>
      <th>Answer options</th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |q| %>
      <tr>
        <td><%= q.id%></td>
        <td><%= q.answer_category_id%></td>
        <td><%= q.survey_answer_option%></td>
      </tr>
    <% end%>
  </tbody>
</table>

app/views/questions/index.html.erb
<%= render 'form' %>
<br>
<li><%= link_to 'To Dashboard Page', root_path %></li>
<br>

app/views/questions/new.html.erb
<div>
    <h4>Import Questions data! </h4>
    <%= form_tag import_questions_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import from file" %>
    <% end %>
</div>
<br>
<li><%= link_to 'To Dashboard Page', root_path %></li>
<br>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>    
      <th>Survey Code</th>
      <th>Description</th>
      <th>Question</th>

    </tr>
  </thead>
  <tbody>
    <% @q.each do |q| %>
      <tr>
        <td><%= q.survey_code%></td>
        <td><%= q.survey_desc%></td>
        <td><%= q.survey_question%></td>
      </tr>
    <% end%>
  </tbody>
</table>
<li><%= link_to 'To Dashboard Page', root_path %></li>
<li><%= link_to 'New Survey', new_survey_path %></li>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= form_with scope: :survey, url: surveys_path, local: true do |form| %>
 

<div class="field">
  <%= form.label :survey_code%>
  <%= form.text_field :survey_code%>
</div>

<div class="field">
  <%= form.label :survey_desc%>
  <%= form.text_field :survey_desc%>
</div>



<div class="dropdown">
  <%= form.label :question_id %>
  <% if false %>
  >>>>>This is a comment block
  collection_select(object, method, collection, value_method, text_method)
  * object - is the object that needs to be saved - here 'Survey' which is defined in the form_with hence ommitted
  * method - is what field you want to save - here question_id
  * collection - is which model instance you want to source your drop down from
  * value_method - this is what needs to be saved in the 'method' defined in this         method - here need to save id from question into question_id of the survey 
  * text_method - what should you see in the dropdown.
  >>>>>
  <% end %>
 
  <%= form.collection_select(:question_id,  @questions, :id, :survey_question, {}, {:multiple => true, :width => 2})%> 
</div>

 <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
<br>
<li><%= link_to 'To Dashboard Page', root_path %></li>
<br>